language: scala
scala:
 - 2.11.6
script:
 - sbt ++$TRAVIS_SCALA_VERSION validate
jdk:
 - openjdk7
 - oraclejdk7
 - oraclejdk8
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -y rpm
