language: scala
scala:
- 2.11.7
script:
- sbt ++$TRAVIS_SCALA_VERSION validate
jdk:
- oraclejdk7
- oraclejdk8
before_install:
- sudo apt-get update -qq
- sudo apt-get install -y rpm
after_success:
- bash <(curl -s https://codecov.io/bash)
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/13627e9a6e8fa0dec084 # m-doc/general
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
