language: scala
scala:
- 2.11.7
jdk:
- oraclejdk8
sudo: false
addons:
  apt:
    packages:
    - graphviz
cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt/boot/"
script:
- sbt ++$TRAVIS_SCALA_VERSION validate
after_success:
- bash <(curl -s https://codecov.io/bash)
before_deploy:
- sbt makeBintrayDeploymentDescriptorDeb
deploy:
  provider: bintray
  file: deploy.json
  user:
    secure: W79fU4GPXMuhDhYhoZfHgcss84MDH5vIyaMEBkQwAhUgyC//PX4ACcSdNesR/m8EuHF/j7IMRmKNRJY8ecm4RGRWGiHLvjjrZb1FOr+q+n98vjl+EjQEcfDioA2qXBZ/ilsnoG9ALsmh4mxk+EV7fPYjfmulC4oHVQt4+NCoBCo=
  key:
    secure: NLGSbwIiycOymEWE7dsGXe4KMQrgky2wfC/9tBcpODd/5Xyq1hZoZNeV7/8cNAGxgKlEJD+hkhozIJOUVn78qjuPHkmgq3KFgnAClfhfNUdlXLxBlr9jwkLl/T81aMbZ2NsL6h4L1GWNtWqjT9LNXhVWi8l0i4GdigSzYci85kg=
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/13627e9a6e8fa0dec084 # m-doc/general
    on_success: change
    on_failure: always
    on_start: never
