language: scala
scala:
 - 2.11.7
script:
 - sbt ++$TRAVIS_SCALA_VERSION validate
jdk:
 - oraclejdk7
 - oraclejdk8
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -y rpm
after_success:
 - bash <(curl -s https://codecov.io/bash)
