version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/html2pdf-src
hooks:
  AfterInstall:
    - location: scripts/install-sbt.sh
      timeout: 300
      runas: root
    - location: scripts/start.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 300
      runas: root
